server:
  port: 8081
  ssl:
    key-password: password
    key-store: classpath:keystore
    key-store-password: password
    key-store-type: PKCS12
    key-store-provider: SUN
#    trust-store: classpath:truststore
    trust-store: Backend-App1/src/main/resources/truststore
    trust-store-password: password
    trust-store-type: PKCS12
    trust-store-provider: SUN
    enabled: true
    protocol: TLSv1.3

spring:
  datasource:
    url: jdbc:h2:mem:db-app1
    driverClassName: org.h2.Driver
    username: app1
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

sso:
  authorization:
    url: "https://localhost:9999/api/auth/verify"
  userinfo:
    #TODO proper URL
    url: "https://localhost:9999/api/user/info"
