server:
  port: 8081
  ssl:
    key-password: password
    key-store: classpath:keystore
    key-store-password: password
    key-store-type: PKCS12
    key-store-provider: SUN
    trust-store: classpath:truststore
    trust-store-password: password
    trust-store-type: PKCS12
    trust-store-provider: SUN
    enabled: true
    protocol: TLSv1.3

authorization:
  url: "https://localhost:9999/api/auth/verify"
