server:
  port: 8082
  ssl:
    key-password: password
    key-store: classpath:keystore
    key-store-password: password
    key-store-type: PKCS12
    key-store-provider: SUN
    trust-store: classpath:truststore
    trust-store-password: password
    trust-store-type: PKCS12
    trust-store-provider: SUN
    enabled: true
    protocol: TLSv1.3

spring:
  datasource:
    url: jdbc:h2:mem:db-app2
    driverClassName: org.h2.Driver
    username: app2
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

app:
  name: app2
  frontend:
    url: https://localhost:3002

sso:
  url:
    base: https://localhost:8080
    authorization: ${sso.url.base}/api/auth/verify
    logout: ${sso.url.base}/api/auth/logout
    userinfo: ${sso.url.base}/api/auth/user/info
