server:
  port: 8082
  ssl:
    key-password: password
    key-store: classpath:keystore
    key-store-password: password
    key-store-type: PKCS12
    key-store-provider: SUN
    trust-store: classpath:truststore
    trust-store-password: password
    trust-store-type: PKCS12
    trust-store-provider: SUN
    enabled: true
    protocol: TLSv1.3

app:
  frontend:
    url: https://localhost:3002

sso:
  url:
    base: https://localhost:8080
    authorization: ${sso.url.base}/api/auth/verify
    logout: ${sso.url.base}/api/auth/logout
    userinfo: ${sso.url.base}/api/auth/user/info
  api-key: zOn1klp7Srfhz97RHmqu
  api-credential: app2-credential
