server:
  port: 8080
  ssl:
    key-password: password
    key-store: classpath:keystore
    key-store-password: password
    key-store-type: PKCS12
    key-store-provider: SUN
    enabled: true

security:
  cookie:
    domain: localhost
    otp:
      name: otpCookie
      secret: bot2ofc4Rf
      path: /authorization/otp/login
      expiration-time:
        seconds: 300
    auth:
      name: authCookie
      secret: 4Rfofcbot2
      path: /api
      expiration-time:
        seconds: 1800
app:
  name: DEW_SSO
  frontend:
    url: https://localhost:3000
  clients:
    names: app1, app2
