spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/sso-db
    username: sso
    password: password
  jpa:
#    hibernate:
#      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
