server:
  port: 8080
  ssl:
    key-password: password
    key-store: classpath:keystore
    key-store-password: password
    key-store-type: PKCS12
    key-store-provider: SUN
    enabled: true

security:
  cookie:
    domain: localhost
    otp:
      name: otpCookie
      secret: bot2ofc4Rf
      path: /authorization/otp/login
      expiration-time:
        seconds: 300
    auth:
      name: authCookie
      secret: 4Rfofcbot2
      path: /api
      expiration-time:
        seconds: 1800

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sso
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

app:
  name: DEW_SSO
  frontend:
    url: https://localhost:3000
  clients:
    v7cvQIayD03nBEiNaCmo:
      app-name: app1
      credential: app1-credential
    zOn1klp7Srfhz97RHmqu:
      app-name: app2
      credential: app2-credential
